import { addDays, subDays, formatISO } from 'date-fns';
import type { Product } from './types';

const today = new Date();

export const products: Product[] = [
  {
    id: 'prod_1',
    division: 10,
    itemCode: 'BK-001',
    brand: 'Artisan Bakes',
    description: 'Sourdough Loaf',
    packSize: 12,
    size: '1.5lb',
    minExpiry: formatISO(addDays(today, 15)),
    maxExpiry: formatISO(addDays(today, 25)),
    projectedSellOut: formatISO(addDays(today, 10)),
    quantityOnHand: 150,
    committedQuantity: 25,
  },
  {
    id: 'prod_2',
    division: 20,
    itemCode: 'DY-015',
    brand: 'Farm Fresh',
    description: 'Organic Greek Yogurt',
    packSize: 6,
    size: '5.3oz',
    minExpiry: formatISO(addDays(today, 45)),
    maxExpiry: formatISO(addDays(today, 60)),
    projectedSellOut: formatISO(addDays(today, 40)),
    quantityOnHand: 200,
    committedQuantity: 150,
  },
  {
    id: 'prod_3',
    division: 30,
    itemCode: 'PR-052',
    brand: 'Global Produce',
    description: 'Avocado Hass',
    packSize: 1,
    size: 'ea',
    minExpiry: formatISO(addDays(today, 5)),
    maxExpiry: formatISO(addDays(today, 9)),
    projectedSellOut: formatISO(addDays(today, 3)),
    quantityOnHand: 300,
    committedQuantity: 100,
  },
  {
    id: 'prod_4',
    division: 40,
    itemCode: 'BV-101',
    brand: 'AquaPure',
    description: 'Sparkling Mineral Water',
    packSize: 24,
    size: '12oz',
    minExpiry: formatISO(addDays(today, 180)),
    maxExpiry: formatISO(addDays(today, 365)),
    projectedSellOut: formatISO(addDays(today, 150)),
    quantityOnHand: 500,
    committedQuantity: 50,
  },
  {
    id: 'prod_5',
    division: 50,
    itemCode: 'FZ-033',
    brand: 'Napoli Pizza Co.',
    description: 'Neapolitan Pizza',
    packSize: 1,
    size: '12in',
    minExpiry: formatISO(addDays(today, 88)),
    maxExpiry: formatISO(addDays(today, 120)),
    projectedSellOut: formatISO(addDays(today, 95)),
    quantityOnHand: 120,
    committedQuantity: 80,
  },
  {
    id: 'prod_6',
    division: 60,
    itemCode: 'SN-089',
    brand: 'Salty Snacks',
    description: 'Sea Salt Potato Chips',
    packSize: 30,
    size: '1oz',
    minExpiry: formatISO(addDays(today, 92)),
    maxExpiry: formatISO(addDays(today, 150)),
    projectedSellOut: formatISO(addDays(today, 70)),
    quantityOnHand: 450,
    committedQuantity: 450,
  },
  {
    id: 'prod_7',
    division: 20,
    itemCode: 'DY-004',
    brand: 'Farm Fresh',
    description: 'Whole Milk Gallon',
    packSize: 1,
    size: '1gal',
    minExpiry: formatISO(addDays(today, 12)),
    maxExpiry: formatISO(addDays(today, 18)),
    projectedSellOut: formatISO(addDays(today, 8)),
    quantityOnHand: 80,
    committedQuantity: 10,
  },
    {
    id: 'prod_8',
    division: 70,
    itemCode: 'MT-007',
    brand: 'Prime Cuts',
    description: 'Grass-fed Ribeye Steak',
    packSize: 2,
    size: '8oz',
    minExpiry: formatISO(addDays(today, 8)),
    maxExpiry: formatISO(addDays(today, 14)),
    projectedSellOut: formatISO(subDays(today, 2)),
    quantityOnHand: 40,
    committedQuantity: 5,
  },
  {
    id: 'prod_9',
    division: 10,
    itemCode: 'BK-005',
    brand: 'Artisan Bakes',
    description: 'Croissant',
    packSize: 24,
    size: 'ea',
    minExpiry: formatISO(addDays(today, 2)),
    maxExpiry: formatISO(addDays(today, 4)),
    projectedSellOut: formatISO(addDays(today, 1)),
    quantityOnHand: 250,
    committedQuantity: 200,
  },
  {
    id: 'prod_10',
    division: 30,
    itemCode: 'PR-021',
    brand: 'Global Produce',
    description: 'Organic Bananas',
    packSize: 1,
    size: '40lb',
    minExpiry: formatISO(addDays(today, 6)),
    maxExpiry: formatISO(addDays(today, 10)),
    projectedSellOut: formatISO(addDays(today, 5)),
    quantityOnHand: 400,
    committedQuantity: 350,
  },
  {
    id: 'prod_11',
    division: 20,
    itemCode: 'DY-030',
    brand: 'Farm Fresh',
    description: 'Cheddar Cheese Block',
    packSize: 1,
    size: '2lb',
    minExpiry: formatISO(addDays(today, 75)),
    maxExpiry: formatISO(addDays(today, 90)),
    projectedSellOut: formatISO(addDays(today, 60)),
    quantityOnHand: 180,
    committedQuantity: 90,
  },
  {
    id: 'prod_12',
    division: 40,
    itemCode: 'BV-210',
    brand: 'Morning Buzz',
    description: 'Cold Brew Coffee',
    packSize: 12,
    size: '11oz',
    minExpiry: formatISO(addDays(today, 60)),
    maxExpiry: formatISO(addDays(today, 90)),
    projectedSellOut: formatISO(addDays(today, 45)),
    quantityOnHand: 220,
    committedQuantity: 120,
  },
  {
    id: 'prod_13',
    division: 70,
    itemCode: 'MT-019',
    brand: 'Prime Cuts',
    description: 'Organic Chicken Breast',
    packSize: 4,
    size: '1lb',
    minExpiry: formatISO(addDays(today, 7)),
    maxExpiry: formatISO(addDays(today, 10)),
    projectedSellOut: formatISO(addDays(today, 4)),
    quantityOnHand: 90,
    committedQuantity: 20,
  },
  {
    id: 'prod_14',
    division: 50,
    itemCode: 'FZ-041',
    brand: 'Green Giant',
    description: 'Frozen Peas',
    packSize: 12,
    size: '12oz',
    minExpiry: formatISO(addDays(today, 300)),
    maxExpiry: formatISO(addDays(today, 400)),
    projectedSellOut: formatISO(addDays(today, 250)),
    quantityOnHand: 600,
    committedQuantity: 150,
  },
  {
    id: 'prod_15',
    division: 60,
    itemCode: 'SN-105',
    brand: 'Kettle Brand',
    description: 'Jalapeño Potato Chips',
    packSize: 12,
    size: '8.5oz',
    minExpiry: formatISO(addDays(today, 100)),
    maxExpiry: formatISO(addDays(today, 160)),
    projectedSellOut: formatISO(addDays(today, 80)),
    quantityOnHand: 330,
    committedQuantity: 330,
  },
  {
    id: 'prod_16',
    division: 10,
    itemCode: 'BK-012',
    brand: 'Dave\'s Killer Bread',
    description: '21 Whole Grains and Seeds',
    packSize: 8,
    size: '27oz',
    minExpiry: formatISO(addDays(today, 10)),
    maxExpiry: formatISO(addDays(today, 15)),
    projectedSellOut: formatISO(addDays(today, 7)),
    quantityOnHand: 130,
    committedQuantity: 40,
  },
  {
    id: 'prod_17',
    division: 20,
    itemCode: 'DY-045',
    brand: 'Chobani',
    description: 'Flip Strawberry Cheesecake',
    packSize: 8,
    size: '4.5oz',
    minExpiry: formatISO(addDays(today, 30)),
    maxExpiry: formatISO(addDays(today, 40)),
    projectedSellOut: formatISO(addDays(today, 25)),
    quantityOnHand: 280,
    committedQuantity: 200,
  },
  {
    id: 'prod_18',
    division: 30,
    itemCode: 'PR-088',
    brand: 'Driscoll\'s',
    description: 'Organic Strawberries',
    packSize: 8,
    size: '1lb',
    minExpiry: formatISO(addDays(today, 4)),
    maxExpiry: formatISO(addDays(today, 7)),
    projectedSellOut: formatISO(addDays(today, 2)),
    quantityOnHand: 150,
    committedQuantity: 140,
  },
  {
    id: 'prod_19',
    division: 70,
    itemCode: 'SF-001',
    brand: 'Ocean\'s Catch',
    description: 'Wild Salmon Fillet',
    packSize: 1,
    size: '1.5lb',
    minExpiry: formatISO(addDays(today, 5)),
    maxExpiry: formatISO(addDays(today, 8)),
    projectedSellOut: formatISO(addDays(today, 3)),
    quantityOnHand: 60,
    committedQuantity: 15,
  },
  {
    id: 'prod_20',
    division: 80,
    itemCode: 'CN-001',
    brand: 'Sweet Tooth',
    description: 'Chocolate Chip Cookies',
    packSize: 12,
    size: '13oz',
    minExpiry: formatISO(addDays(today, 90)),
    maxExpiry: formatISO(addDays(today, 120)),
    projectedSellOut: formatISO(addDays(today, 60)),
    quantityOnHand: 300,
    committedQuantity: 100,
  },
  {
    id: 'prod_21',
    division: 80,
    itemCode: 'CN-002',
    brand: 'Sweet Tooth',
    description: 'Oatmeal Raisin Cookies',
    packSize: 12,
    size: '13oz',
    minExpiry: formatISO(addDays(today, 90)),
    maxExpiry: formatISO(addDays(today, 120)),
    projectedSellOut: formatISO(addDays(today, 65)),
    quantityOnHand: 280,
    committedQuantity: 0,
  },
  {
    id: 'prod_22',
    division: 40,
    itemCode: 'BV-300',
    brand: 'Pure Leaf',
    description: 'Unsweetened Black Tea',
    packSize: 6,
    size: '16.9oz',
    minExpiry: formatISO(addDays(today, 200)),
    maxExpiry: formatISO(addDays(today, 300)),
    projectedSellOut: formatISO(addDays(today, 180)),
    quantityOnHand: 400,
    committedQuantity: 200,
  }
];
